// Domain types are generated from crates/core by ts-rs (`make rust-bindings`);
// don't edit src/generated by hand. The venue adapters themselves are Rust.
export type * from "./generated/domain";
export {
  isValidAccount,
  type SecretStore,
  SecretStoreError,
  type SecretStoreErrorKind,
  withSecret,
} from "./secrets";
